kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.name }}-keys
data:
{{ (.Files.Glob "keys/keystore.jks").AsSecrets | indent 2 }}
{{ (.Files.Glob "keys/server.truststore").AsSecrets | indent 2 }}
type: Opaque
