---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
    name: {{ $.Values.name }}
spec:
  ports:
    - name: {{ $.Values.port }}-tcp
      protocol: TCP
      port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
  selector:
    app: {{ $.Values.name }}
  type: ClusterIP
  sessionAffinity: None